### ISSUE TITLE
vzctl snapshot creation

### ISSUE THREAD

**Issue by d6v3w** [websavers/centos2alma_openvz#1]
**Virtuozzo release 7.5.4 (465)**

Had a problem with this part of the code on almaconvert8-plesk;

`           snaphost_out = subprocess.check_output(['/bin/prlctl', 'snapshot', ct, '-n', 'Pre-Almalinux8', '-d', 'Created automatically by almaconvert8 tool at %s' % now])`
`            snaphost_out = subprocess.check_output(['/sbin/vzctl', 'snapshot', ct, '--name', 'Pre-Almalinux8', '-d', 'Created automatically by almaconvert8 tool at %s' % now])
`

changed it to

`           snaphost_out = subprocess.check_output(['/bin/prlctl', 'snapshot', ct, '-n', 'Pre-Almalinux8', '-d', 'Created automatically by almaconvert8 tool at %s' %now])`
 `            snaphost_out = subprocess.check_output(['/sbin/vzctl', 'snapshot', ct, '--name', 'Pre-Almalinux8'])
`
*removed the space between % and now])
*removed the -d from the vzctl line as vzctl snapshot doesn't accept a description.

**Comment by d6v3w** [comment]
Fixed this by removing /root/almaconvert8-plesk
```rm -f /root/almaconvert8-plesk```

uninstall vzdeploy8
``` yum remove vzdeploy8```

installed an earlier version;
```yum install vzdeploy8-1.0.61-10.vl7```

And ran the script again.

**Comment by jas8522** [comment]
This is all stuff I never encountered. The version of vzdeploy installed when I ran my conversions (test and live) has been `vzdeploy8-1.0.64-1.vz7.noarch`

I suspect this is because prlctl works on our systems and so it doesn't need to fallback to the vzct 'except' part - do you not have it? Is it a very old version of OpenVZ?

It should work with `--description` rather than `-d` -- could you try that to confirm? If it does, then I'd recommend creating a bug report at https://bugs.openvz.org indicating that the vzctl switch is used wrong!
